name: Test and Publish

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  workflow_dispatch: {}
  pull_request: {}

jobs:
  test:
    name: Test
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: true

    - name: Install dependencies
      run: pdm install -d

    - name: Lint with ruff
      run: pdm run ruff check src

    - name: Test with pytest
      run: pdm run pytest -v

  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    needs: test
    if: >-
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.x"
          cache: true

      - name: Build a binary wheel and a source tarball
        run: pdm build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}